# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b70b19dcb3dc33c33615944dd3396c29259ec0874cfbb8dcc7fc6727a2ce3d8a3725a338191d2de5b024d2719464b623830a0d6f0be9a0bcf4df14ea07fb1608

test:
  secret_key_base: dd2f6c88809cae8819d2ea3edd3ca2e7c6cd8002b9ab5a0d1c28dbb4a7aeae3247e5c393ca3a2fbb261d533c115097432e1eaa70c2684a444f6002be0cf086a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
